export const SOCKET_EVENTS = {
    JOIN: "ooa join",
    PLAY_SINGLE: "ooa play single mode",
    EXIT_ROOM: "ooa exit",
    UPGRADE_SPELL: "ooa upgrade spell",

    LOBBY_DATA: "ooa lobby data",
    START_GAME: "ooa start game",
    TOWER_STATUS: "ooa tower status",
    PRODUCE_BOT: "ooa produce bot",
    BOT_STATUS: "ooa bot status",
    RECEIVE_UPGRADES: "ooa receive upgrades",
    TICK_SECOND: "ooa tick second",
    TICK_ROUND: "ooa tick round",
    ADD_SPRITE: "ooa add sprite",
    ADD_TEXT_SPRITE: "ooa add text sprite",
    ADD_SPRITE_COLLISION_EFFECT: "ooa add sprite collision effect",
    DISPOSE_SPRITE: "ooa dispose sprite",
    SPRITE_STATUS: "ooa sprite state",
    KILL_BOT: "ooa kill bot",
    REMOVE_DEAD_BOTS: "ooa remove dead bots",
};
